[package]
name = "lwm2m-server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "^1.44", features = ["macros", "net", "rt", "sync"]}
coap-lite = "^0.13.1"
async-trait = "0.1.88"

[dev-dependencies]
cargo-llvm-cov = "0.6.16"

