name: Build and Test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        rust_version: ["stable", "nightly", "1.81"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rustup update
        rustup install ${{ matrix.rust_version }}
        rustup default ${{ matrix.rust_version }}

    - name: Build
      run: |
        cargo --version
        rustc --version
        cargo build --verbose

    - name: Test
      run: |
        cargo --version
        cargo test --verbose

    - name: Clippy
      run: |
        cargo clippy --version
        cargo clippy --all-targets --all-features -- -D warnings

    - name: rustfmt
      run: |
        cargo fmt --version
        cargo fmt --all -- --check

    - name: pre-commit
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip install pre-commit==4.2.0
        pre-commit run --all-files
      working-directory: .
